### PR TITLE
Fix various Zba bugs

### PR DESCRIPTION
**Pull request by PRugg-Cap**
Fixes https://github.com/riscv/riscv-cheri/issues/159

### CODE REVIEW

**Review by arichardson — APPROVED** [review]
LGTM will merge once one more reviewer has approved it. 

Note when merging: update commit message (or use rebase and merge)

**Review by andresag01 — APPROVED** [review]

**Comment by tariqkurd-repo** [comment]
@PRugg-Cap this is the source of the CSV file: https://docs.google.com/spreadsheets/d/1PsWkaqRM2PiXKl7f9EegCjEsb4CVuvnZdIeJeFPyBDw/edit#gid=0

I made the changes there and reimported by running `make download -B`

**Comment by tariqkurd-repo** [comment]
@veselypeta opinion?

**Comment by veselypeta** [comment]
LGTM :)

**Comment by arichardson** [comment]
It would have been good to include the specific bugs that were fixed in the commit message or use rebase and merge

**Pull request merged**
