### PR TITLE
removed redundant word "possible" in the text

### PR DESCRIPTION
**Pull request by IIITM-Jay**
## Description
This PR intends to improve a minor sentence in the text of **_Anatomy of Capabilities in Zcheripurecap_** as a **_NOTE_**.

### Changes Made
The word _"possible"_ was redundant, so it was removed to improve conciseness.

### CODE REVIEW

**Comment by tariqkurd-repo** [comment]
hi - are you a risc-v member as it says on your profile?

**Comment by IIITM-Jay** [comment]
Hi @tariqkurd-repo  , Yes, I joined as a Mentee under RISC_V Mentorship programme Fall 2024.

**Comment by tariqkurd-repo** [comment]
pushed into another PR

**Comment by IIITM-Jay** [comment]
Hi @tariqkurd-repo , I do see that the change in this PR is being included in the PR #427 , in the last commit as [remove duplicate word](https://github.com/riscv/riscv-cheri/pull/427/commits/354e91306b57b29a7f70bda1cc78d323bbda01ed), but this removes my authorship for the change I did in this PR, It would be better if you could retain my authorship there. 

> pushed into another PR

By your comment, it seemed that this change was merged into another PR with my commit as an author.

Thanks!

**Pull request closed without merging**
