### PR TITLE
Fix malformed check to avoid 65-bit top overflow

### PR DESCRIPTION
**Pull request by PRugg-Cap**
Hopefully addresses https://github.com/riscv/riscv-cheri/issues/149, but I'd like to do some more checking before this gets merged!

### CODE REVIEW

**Review by tariqkurd-repo — APPROVED** [review]
nice and simple

**Comment by arichardson** [comment]
Does this also mean we can no longer observe BASE > TOP for all tagged capabilities?

**Comment by PRugg-Cap** [comment]
> Does this also mean we can no longer observe BASE > TOP for all tagged capabilities?

Depends what you mean... This means that in 65-bits, BASE <= TOP, tagged or untagged. For tagged capabilities, that was (hopefully!) already true, even in a 64-bit space, with the exception of 2^64 itself. Note though that there isn't a CGetTop (GCTop?), so software would have to do base + length itself, with length saturating at uint_max.

**Comment by arichardson** [comment]
> Depends what you mean... This means that in 65-bits, BASE <= TOP, tagged or untagged. For tagged capabilities, that was (hopefully!) already true, even in a 64-bit space, with the exception of 2^64 itself. Note though that there isn't a CGetTop (GCTop?), so software would have to do base + length itself, with length saturating at uint_max.

Yes I mean in 65-bit space. I vaguely remember seeing cases in the cheri-compressed-cap library where use of the high bits would infer a top < base due to wrapping, so we couldn't assert that the decompressed top > decompressed base in all cases.

**Comment by PRugg-Cap** [comment]
@arichardson Yes, that's exactly the problem this is to fix.

**Comment by PRugg-Cap** [comment]
As with https://github.com/riscv/riscv-cheri/pull/116#issuecomment-2047932173 I've proved that the decoded bounds from encoded capabilities always have `base <= top`. It finds the problem before this fix and proves the property after this fix. Same caveats apply, including that I've had to change the SMT backend.

This should be good to merge.

**Comment by PRugg-Cap** [comment]
... Now with better whitespace.

**Pull request merged**
