### PR TITLE
correct prerequisite rules

### PR DESCRIPTION
**Pull request by tariqkurd-repo**
Addresses https://github.com/riscv/riscv-cheri/issues/29

### CODE REVIEW

**Comment by sorear** [comment]
Zcd or D doesn't make much sense, Zcd implies D?

**Comment by tariqkurd-repo** [comment]
>Zcd or D doesn't make much sense, Zcd implies D?

You can specify either. Zcd implies D, and D will infer C.FSDSP etc. if C or Zca are included even if Zcd isn't included.
It's weird but that's how it is.

**Comment by jrtc27** [comment]
> > Zcd or D doesn't make much sense, Zcd implies D?
> 
> You can specify either. Zcd implies D, and D will infer C.FSDSP etc. if C or Zca are included even if Zcd isn't included. It's weird but that's how it is.

Which is sorear's point: that Zcd || D is entirely equivalent to D as a boolean expression given Zcd implies D. I think what you want here to make it *not* weird (other than due to the retroactive splitting of C) is Zcd or DC.

I don't think you're right that DZca infers Zcd though? LLVM doesn't do that, and I don't see why it would. Isn't the whole point of Zca to let you not have things like Zcd?

**Comment by tariqkurd-repo** [comment]
Oh yes you're right, apologies.
Will fix tomorrow

Tariq

**Pull request merged**
