### PR TITLE
remove pcc + 4 for the next PC, as it's not always correct

### PR DESCRIPTION
**Pull request by tariqkurd-repo**

### CODE REVIEW

**Comment by tariqkurd-repo** [comment]
as @francislaus pointed out, sometimes the use of <<pcc>> + 4 for the next instruction was incorrect, so I've removed all references as they were redundant anyway

**Comment by tariqkurd-repo** [comment]
fixes https://github.com/riscv/riscv-cheri/issues/300

**Review by arichardson — APPROVED** [review]

**Comment by francislaus** [comment]
Thanks for doing that change @tariqkurd-repo. I think the description of `C.JAL` does not always not refer to `JAL`. Can we change that?

**Comment by francislaus** [comment]
Ah, I see @arichardson just merged

**Comment by francislaus** [comment]
I was about to suggest "See <<JAL>> for execution of the expanded instruction as shown above." for the descriptions. Can we fit that in somehow?

**Comment by tariqkurd-repo** [comment]
image

Both lines could be the same - the cap mode one couls also refer to the JAL definition.

**Pull request merged**
