### PR TITLE
Add draft specification proposal from Codasip

### PR DESCRIPTION
**Pull request by andresag01**
This change is a draft proposal with CHERI extensions for RISC-V. These are the following extensions being proposed:

* **Zcheri_purecap:** Introduces key, minimal CHERI concepts and features to the RISC-V ISA. The resulting extended ISA is not backwards-compatible with RISC-V
* **Zcheri_legacy:** Extends Zcheri_purecap with features to ensure that the ISA extended with CHERI allows backwards binary compatibility with RISC-V
* **Zcheri_mode:** Adds a mode bit in the encoding of capabilities to allow changing the current CHERI execution mode using indirect jump instructions
* **Zcheri_pte:** CHERI extension for RISC-V harts supporting page-based virtual-memory

@tariqkurd-repo @arichardson

### CODE REVIEW

**Review by tariqkurd-repo — APPROVED** [review]
This document is the culmination of many months of work from several people.
I'd like @arichardson to merge it if he's happy.
The SAIL inserts are missing, otherwise I think it's quite complete as a techncial specification.

**Review by arichardson — COMMENTED** [review]
Thanks for submitting this PR! I've started reviewing it and will leave comments shortly. I think we can probably merge the initial version and send it out for review before those have been addressed but I'd like to finish reading the entire document before I click merge.

**Comment by tariqkurd-repo** [comment]
No problem @arichardson , best to read the whole thing before merging, and then we can start discussing. This is a live spec so having it merged will make fixing issues easier.

**Comment by vmurali** [comment]
Hi all, is github PR comments the forum to discuss the spec?

**Comment by tariqkurd-repo** [comment]
I hope we can merge by the end of this week and then start filing issues and PRs for discussion. @arichardson is reading the whole spec first.

**Comment by arichardson** [comment]
I am almost done with my readthrough and plan to merge by the end of this week. So far I've only spotted minor issues that can be fixed incrementally.

**Comment by vmurali** [comment]
No hurry! I was just asking where one should be discussing the spec as this is the first major PR after the initial commit, and there are no issues so far in this repo.

Looks like the suggested approach for comments/discussion is via this repo's issues and submitting PR's.

**Review by arichardson — APPROVED** [review]
I've completed my read of the spec and just wanted to say this is fantastic work!

I have some smaller comments that I'll file as GitHub issues of the coming days, but nothing that should block merging this initial version.

**Pull request merged**
